name: AQI Data Chart

on:
  schedule:
    - cron: '0 * * * *'  # Chạy mỗi giờ (có thể thay đổi theo nhu cầu)
  workflow_dispatch:  # Cho phép chạy thủ công từ GitHub Actions

jobs:
  crawl-and-plot:
    runs-on: ubuntu-latest

    steps:
      # Check out repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cài đặt Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Cài đặt dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib

      # Chạy vẽ biểu đồ
      - name: Run AQI plotting
        run: |
          python CityCharts.py # Chạy file vẽ biểu đồ

      # Commit kết quả mới vào repo nếu có thay đổi (file hình ảnh và CSV)
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A 
          git commit -m "Update AQI data and charts" || echo "No changes to commit"
          git push
