name: AQI Data Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Cho phép chạy thủ công từ GitHub UI

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy matplotlib seaborn scikit-learn

    - name: Run AQI analysis script
      run: |
        python data_relationship.py # Thay tên file script của bạn nếu cần

    - name: Commit and push CSV
      run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data.csv
          git commit -m "Update AQI data - $(date -u '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git pull origin main --rebase
          git push origin main

    
